# Python Course Notebook 21 fev 2025

This notebook covers fundamental Python concepts including variables, loops, data structures, functions, and NumPy operations.


## 1. Variables and Data Types

In [3]:
x = 'Bonjour'  # String variable

In [4]:
type(x)  # Check the type of x

str

## 2. Loops and Iterations

In [5]:
# Loop through each character in the string
for i in range(0, len(x)):
    print(x[i])

B
o
n
j
o
u
r


## 3. Lists and Enumerations

In [6]:
l = [1, 2, -3, 'abc', [1, 2, 3]]  # A list containing multiple data types

In [7]:
# Iterate through the list and print each element
for e in l:
    print(e)

1
2
-3
abc
[1, 2, 3]


In [8]:
# Using enumerate to print even indexed elements
for index, value in enumerate(l):
    if index % 2 == 0:
        print(index, ':', value)

0 : 1
2 : -3
4 : [1, 2, 3]


## 4. Functions

In [9]:
def repetition(message, nb):
    """Function to print a message multiple times"""
    print(message * nb)

## 5. Tuples and Performance Comparison

In [10]:
import time

# Creating a list and a tuple
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# Measuring access time for the list
start_time = time.time()
for _ in range(1000000):
    my_list[2]
list_access_time = time.time() - start_time

# Measuring access time for the tuple
start_time = time.time()
for _ in range(1000000):
    my_tuple[2]
tuple_access_time = time.time() - start_time

print(f"List access time: {list_access_time}")
print(f"Tuple access time: {tuple_access_time}")

List access time: 0.07111620903015137
Tuple access time: 0.10953712463378906


## 6. Dictionaries

In [11]:
user1 = {'firstname': 'Clark', 'lastname': 'Kent', 'job': 'journalist'}  # Dictionary definition

In [12]:
# Looping through dictionary values
for v in user1.values():
    print(v)

Clark
Kent
journalist


## 7. List Comprehension

In [13]:
# List comprehension example: Squares in descending order
ex1 = [i**2 for i in range(100, 0, -1)]
print(ex1)

[10000, 9801, 9604, 9409, 9216, 9025, 8836, 8649, 8464, 8281, 8100, 7921, 7744, 7569, 7396, 7225, 7056, 6889, 6724, 6561, 6400, 6241, 6084, 5929, 5776, 5625, 5476, 5329, 5184, 5041, 4900, 4761, 4624, 4489, 4356, 4225, 4096, 3969, 3844, 3721, 3600, 3481, 3364, 3249, 3136, 3025, 2916, 2809, 2704, 2601, 2500, 2401, 2304, 2209, 2116, 2025, 1936, 1849, 1764, 1681, 1600, 1521, 1444, 1369, 1296, 1225, 1156, 1089, 1024, 961, 900, 841, 784, 729, 676, 625, 576, 529, 484, 441, 400, 361, 324, 289, 256, 225, 196, 169, 144, 121, 100, 81, 64, 49, 36, 25, 16, 9, 4, 1]


## 8. NumPy Arrays

In [14]:
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, -5, 6])

# Vector operations
print(u + v)  # Vector addition
print(2 * u)  # Scalar multiplication
print(-v)  # Negation

[ 5 -3  9]
[2 4 6]
[-4  5 -6]


## 9. Dot Product and Matrix Operations

In [17]:
# define u and v
u = np.array([1, 2, 3])
v = np.array([4, -5, 6])

In [18]:
# Dot product
print(np.dot(u, v))

12


In [21]:
# Dot product
print(u @ v)

12


In [31]:
M = np.array([[1,2], [3,4], [5,6]])
v = np.array([1, 2])
print(M @ v)  # Matrix-vector multiplication

[ 5 11 17]


# Other usefull libs
- Numpy
- PuLP
- CPLEX
- Pandas
- Gurobi
- Matplotlib