Python 4A 21 fev 2025

In [128]:
x='Bonjour'

In [129]:
type(x)

str

In [130]:
for i in range(0,len(x)):
    print(x[i])

B
o
n
j
o
u
r


In [131]:
l = [1, 2, -3, 'abc', [1, 2, 3]]

In [132]:
for e in l:
    print(e)

1
2
-3
abc
[1, 2, 3]


In [133]:
for index, value in enumerate(l):
    if (index%2 == 0):
        print(index, ':' , value)

0 : 1
2 : -3
4 : [1, 2, 3]


In [134]:
x=2

In [135]:
x%2

0

In [136]:
for index, item in enumerate(l):
    if (index%2 == 0):
        print(index, ':' , item)
    elif (index > 1):
        print('yo !')
    else:
        print(item + item)

0 : 1
4
2 : -3
yo !
4 : [1, 2, 3]


In [137]:
for i in range(0, 2):
    print(l.pop())

[1, 2, 3]
abc


In [138]:
l = [1, 2, -3, 'abc', [1, 2, 3]]

In [139]:
def repetition(message, nb):
    print(message*nb)

In [140]:
l

[1, 2, -3, 'abc', [1, 2, 3]]

In [141]:
l.insert(2, 'hello')

In [142]:
l

[1, 2, 'hello', -3, 'abc', [1, 2, 3]]

In [143]:
ex_tuple = (1, 2, 3)

## Tuple are faster than list due to fixed memory allocation
Test de vitesse

In [144]:
import time

# Creating a list and a tuple with the same elements
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# Measuring access time for the list
start_time = time.time()
for _ in range(1000000):
    my_list[2]
list_access_time = time.time() - start_time

# Measuring access time for the tuple
start_time = time.time()
for _ in range(1000000):
    my_tuple[2]
tuple_access_time = time.time() - start_time

print(f"List access time: {list_access_time}")
print(f"Tuple access time: {tuple_access_time}")

List access time: 0.05547738075256348
Tuple access time: 0.05984926223754883


In [145]:
my_list[-1]

10

In [146]:
user1 = {'firstname':'Clark', 'lastname':'Kent', 'job':'journalist'}

In [147]:
user1

{'firstname': 'Clark', 'lastname': 'Kent', 'job': 'journalist'}

In [148]:
for v in user1.values():
    print(v)

Clark
Kent
journalist


In [149]:
for k in user1.keys():
    print(k)

firstname
lastname
job


In [150]:
for k, v in user1.items():
    print(k, ':', v)

firstname : Clark
lastname : Kent
job : journalist


In [151]:
l

[1, 2, 'hello', -3, 'abc', [1, 2, 3]]

In [152]:
[v*2 for v in l]

[2, 4, 'hellohello', -6, 'abcabc', [1, 2, 3, 1, 2, 3]]

In [153]:
if (800 == 800.0):
    print('yes')
else:
    print('no')

yes


In [154]:
type(800)

int

In [155]:
type(800.0)

float

In [156]:
800 + 800.0

1600.0

# Exercice
-> Ecrire la compréhension de liste qui regroupe les carrés de tous les nombres entre 1 et 100 dans l'ordre décroissant

In [157]:
ex1 = [i**2 for i in range(100, 0, -1)]
print(ex1)

[10000, 9801, 9604, 9409, 9216, 9025, 8836, 8649, 8464, 8281, 8100, 7921, 7744, 7569, 7396, 7225, 7056, 6889, 6724, 6561, 6400, 6241, 6084, 5929, 5776, 5625, 5476, 5329, 5184, 5041, 4900, 4761, 4624, 4489, 4356, 4225, 4096, 3969, 3844, 3721, 3600, 3481, 3364, 3249, 3136, 3025, 2916, 2809, 2704, 2601, 2500, 2401, 2304, 2209, 2116, 2025, 1936, 1849, 1764, 1681, 1600, 1521, 1444, 1369, 1296, 1225, 1156, 1089, 1024, 961, 900, 841, 784, 729, 676, 625, 576, 529, 484, 441, 400, 361, 324, 289, 256, 225, 196, 169, 144, 121, 100, 81, 64, 49, 36, 25, 16, 9, 4, 1]


In [158]:
l = [400,0, -3, 1000, 'abc']

In [159]:
[(x, y) for x in l for y in ex1]

[(400, 10000),
 (400, 9801),
 (400, 9604),
 (400, 9409),
 (400, 9216),
 (400, 9025),
 (400, 8836),
 (400, 8649),
 (400, 8464),
 (400, 8281),
 (400, 8100),
 (400, 7921),
 (400, 7744),
 (400, 7569),
 (400, 7396),
 (400, 7225),
 (400, 7056),
 (400, 6889),
 (400, 6724),
 (400, 6561),
 (400, 6400),
 (400, 6241),
 (400, 6084),
 (400, 5929),
 (400, 5776),
 (400, 5625),
 (400, 5476),
 (400, 5329),
 (400, 5184),
 (400, 5041),
 (400, 4900),
 (400, 4761),
 (400, 4624),
 (400, 4489),
 (400, 4356),
 (400, 4225),
 (400, 4096),
 (400, 3969),
 (400, 3844),
 (400, 3721),
 (400, 3600),
 (400, 3481),
 (400, 3364),
 (400, 3249),
 (400, 3136),
 (400, 3025),
 (400, 2916),
 (400, 2809),
 (400, 2704),
 (400, 2601),
 (400, 2500),
 (400, 2401),
 (400, 2304),
 (400, 2209),
 (400, 2116),
 (400, 2025),
 (400, 1936),
 (400, 1849),
 (400, 1764),
 (400, 1681),
 (400, 1600),
 (400, 1521),
 (400, 1444),
 (400, 1369),
 (400, 1296),
 (400, 1225),
 (400, 1156),
 (400, 1089),
 (400, 1024),
 (400, 961),
 (400, 900),
 (400, 

In [160]:
list2list = [[1,2,3], [4,5,6], [7,8,9]]

In [161]:
list2list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [162]:
list2list[2][2]

9

In [163]:
list2list[-1][-1]

9

In [164]:
import numpy as np

In [165]:
u = np.array([1,2,3])

In [166]:
u

array([1, 2, 3])

In [167]:
v = np.array([4,-5,6])


In [168]:
u+v

array([ 5, -3,  9])

In [169]:
2*u

array([2, 4, 6])

In [170]:
-v

array([-4,  5, -6])

In [171]:
v

array([ 4, -5,  6])

In [172]:
-v

array([-4,  5, -6])

In [173]:
2 * u - v

array([-2,  9,  0])

In [174]:
u

array([1, 2, 3])

In [175]:
v

array([ 4, -5,  6])

Produit scalaire avec @

In [179]:
u @ v

np.int64(12)

In [180]:
u = np.array([1,0])
v = np.array([0,1])

In [181]:
u@v

np.int64(0)

In [182]:
u.dot(v)

np.int64(0)

In [183]:
v.dot(u)


np.int64(0)

In [184]:
np.dot(u, v)

np.int64(0)

In [185]:
M = np.array([[1,2], [3,4], [5,6]])

In [186]:
M

array([[1, 2],
       [3, 4],
       [5, 6]])

In [187]:
u

array([1, 0])

In [188]:
M @ u

array([1, 3, 5])

### fin